# 可以设置为vi或emacs
set-window-option -g mode-keys vi

# set-window-option -g utf8 on #开启窗口的UTF-8支持
# bind Escape copy-mode # 绑定esc键为进入复制模式

# 绑定v键为开始选择文本
bind -T copy-mode-vi v send-keys -X begin-selection
# 绑定y键为复制选中文本
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# bind p pasteb # 绑定p键为粘贴文本（p键默认用于进入上一个窗口，不建议覆盖）
