# ============================ Pastel Powerline ============================
# format = """
# [](#9A348E)\
# $os\
# $username\
# [](bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [](fg:#FCA17D bg:#86BBD8)\
# $c\
# $elixir\
# $elm\
# $golang\
# $gradle\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# $python\
# $conda\
# [](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [](fg:#06969A bg:#33658A)\
# $time\
# [ ](fg:#33658A)\
# """
#
# # Disable the blank line at the start of the prompt
# # add_newline = false
#
# # You can also replace your username with a neat symbol like   or disable this
# # and use the os module below
# [username]
# show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
# format = '[$user ]($style)'
# disabled = false
#
# # An alternative to the username module which displays a symbol that
# # represents the current operating system
# [os]
# style = "bg:#9A348E"
# disabled = true      # Disabled by default
#
# [directory]
# style = "bg:#DA627D"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# # Here is how you can shorten some long paths by text replacement
# # similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# # Keep in mind that the order matters. For example:
# # "Important Documents" = " 󰈙 "
# # will not be replaced, because "Documents" was already substituted before.
# # So either put "Important Documents" before "Documents" or use the substituted version:
# # "Important 󰈙 " = " 󰈙 "
#
# [c]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [docker_context]
# symbol = " "
# style = "bg:#06969A"
# format = '[ $symbol $context ]($style)'
#
# [elixir]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [elm]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [git_branch]
# symbol = ""
# style = "bg:#FCA17D"
# format = '[ $symbol $branch ]($style)'
#
# [git_status]
# style = "bg:#FCA17D"
# format = '[$all_status$ahead_behind ]($style)'
#
# [golang]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [gradle]
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [haskell]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [java]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [julia]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [nim]
# symbol = "󰆥 "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [rust]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [scala]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [time]
# disabled = false
# time_format = "%R"             # Hour:Minute Format
# style = "bg:#33658A"
# format = '[ ♥ $time ]($style)'
#
# [python]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [conda]
# symbol = "🅒"
# style = "bg:#86BBD8"
# format = '[\($symbol ($environment)\) ]($style)'
# ==========================================================================


# ============================ pills ============================
format = """\
[╭╴](fg:arrow)\
$username\
$directory\
$time\
(\
    $git_branch\
    $git_status\
)\
(\
    $python\
    $conda\
    $nodejs\
)\
$cmd_duration
[╰─](fg:arrow)$character\
"""
# Add the modules you need

# Disables the blank line at the start of the prompt
add_newline = true


# Palettes:
#   old: the previous version.
#   normal: dark gray / yellow / white palette.
#   light: pastel light colors.
# To change the colors: change to the corresponding palette.
palette = "old"


[palettes.old]
arrow = "#FF0000"      # "#353535"
os = "#3778BF"
os_admin = "#6A040F"
directory = "#3F37C9"
node = "green"
time = "#177E89"
git = "#B02B10"
git_status = "#8B1D2C"
python = "#3776AB"
conda = "#3EB049"
java = "#861215"
rust = "#C33C00"
clang = "#00599D"
duration = "yellow"
text_color = "#EDF2F4"
text_light = "#EDF2F4"

[palettes.normal]
arrow = "#353535"
os = "#2C3032"
os_admin = "#6A040F"
directory = "#363C3E"
time = "#474D5C"
node = "#F1DEA9"
git = "#D0DBDA"
git_status = "#DFEBED"
python = "#F5CB5C"
conda = "#3EB049"
java = "#861215"
rust = "#C33C00"
clang = "#00599D"
duration = "#F4FBFF"
text_color = "#EDF2F4"
text_light = "#26272A"

[palettes.light]
arrow = "#353535"
os = "#F7768E"
os_admin = "#ACBEF1"
directory = "#FF9578"
time = "#FFDC72"
git = "#F5F5F5"
git_status = "#72FFD5"
clang = "#67E3FF"
java = "#FF52A3"
python = "#B4F9F8"
node = "#81FF85"
conda = "#BAF5C0"
duration = "#91FFE7"
text_color = "#26272A"
text_light = "#26272A"

[username]
style_user = 'os'
style_root = 'os_admin'
format = '[]($style)[  mou](bg:$style fg:text_color)[]($style)'
disabled = false
show_always = true

[character]
success_symbol = "[󰍟](fg:arrow)"
error_symbol = "[󰍟](fg:red)"

[directory]
format = " [](fg:directory)[  $path ]($style)[$read_only]($read_only_style)[](fg:directory)"
truncation_length = 2
style = "fg:text_color bg:directory"
read_only_style = "fg:text_color bg:directory"
before_repo_root_style = "fg:text_color bg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "  "

[time]
disabled = false
format = " [](fg:time)[ $time]($style)[](fg:time)"
time_format = "%H:%M"
style = "fg:text_color bg:time"

[cmd_duration]
format = " [](fg:duration)[ $duration]($style)[](fg:duration)"
style = "fg:text_light bg:duration"
min_time = 500

[git_branch]
format = " [](fg:git)[$symbol$branch](fg:text_light bg:git)[](fg:git)"
symbol = " "

[git_status]
format = '([ ](fg:git_status)[ $all_status$ahead_behind ]($style)[](fg:git_status))'
style = "fg:text_light bg:git_status"

[docker_context]
disabled = true
symbol = " "

[package]
disabled = true

[java]
format = "[ ](fg:java)[$symbol$version](bg:java fg:text_color)[](fg:java)"
version_format = "${raw}"
symbol = " "
disabled = true

[nodejs]
format = "[ ](fg:node)[$symbol$version]($style)[](fg:node)"
style = "bg:node fg:text_light"
symbol = " "
version_format = "${raw}"
disabled = false

[rust]
format = "[ ](fg:rust)[$symbol$version](bg:rust fg:text_color)[](fg:rust)"
symbol = " "
version_format = "${raw}"
disabled = true

[python]
disabled = false
format = '[ ](fg:python)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[](fg:python)'
symbol = " "
version_format = "${raw}"
style = "fg:text_light bg:python"

[conda]
format = "[ ](fg:conda)[$symbol$environment]($style)[](fg:conda)"
style = "bg:conda fg:text_color"
ignore_base = false
disabled = false
symbol = " "

[c]
format = "[ ](fg:clang)[$symbol($version(-$name) )](bg:clang fg:text_color)[](fg:clang)"
symbol = " "
version_format = "${raw}"
disabled = true

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
# ==========================================================================
