return {
  -- {
  --   "zbirenbaum/copilot.lua",
  --   cmd = "Copilot",
  --   event = "InsertEnter",
  --   config = function()
  --     require("copilot").setup({
  --       suggesion = { enabled = false },
  --       panel = { enabled = false }
  --     })
  --   end,
  -- },
  -- "zbirenbaum/copilot-cmp",
  -- dependencies = {
  --   "zbirenbaum/copilot.lua",
  --   "hrsh7th/nvim-cmp"
  -- },
  -- config = function()
  --   require("copilot_cmp").setup()
  -- end
}
